name: ğŸ’¢ ğŸ‡¨ğŸ‡» deploy & quality

on:
 push:
   - main 
 worlflow_dispactch:

permissions:
   contents: read
   pages: write
   id-token: write

concurrency:
group: ${{ github.worlflow}}-${{github.ref}}
cancel-in-progresso: true

jobs:
 deploy:
   name: ğŸ’€
   runs-on: ubuntu-latest
   if: github ref == 'refs/heads/main'
   ouputs:
    page_url: ${{ steps.deployment.ouputs.page_url }}

   environment:
   name: github-pages
   url: ${{ steps.deployment.ouputs.page_url }}

   steps:
   -name: ğŸŒ„ checkout code
      user: actions/checkout@v4

   -name: ğŸ–‡ï¸ setup pages
    user: actions/cofigure-pages@v4


   -name: ğŸ–‡ï¸ upload artifact
   user: actions/upload-pages-artifact@v4
   with:
    path: "." 
   -name: ğŸ€„ Deploy to Github Pages 
   id: deployment
   uses:actions/deployment-pages@v4